Build: use multi-stage to support new version and multi platform
Docker-Hub-frolvlad/docker-alpine-glibc pull request #74
Opened 2024-12-31 05:45 UTC by ChaimHong

#73

2025-01-01 23:10 UTC, frol requested changes
@ChaimHong Thank you for the contribution! Please, address my review comments and meanwhile I will test it on my side.

@race-of-sloths invite @ChaimHong

2025-01-01 23:10 UTC, frol commented on APKBUILD
> +  esac
Will this work just fine?

```suggestion
  ln -s "/usr/glibc-compat/lib/ld-linux-${arch}.so.2" "${pkgdir}/lib/ld-linux-${arch}.so.2"
  ln -s "/usr/glibc-compat/lib/ld-linux-${arch}.so.2" "${pkgdir}/usr/glibc-compat/lib64/ld-linux-${arch}.so.2"
```

2025-01-01 23:10 UTC, frol commented on Dockerfile
> +FROM alpine:3.20 AS remote-builder
What is the use of this "remote-builder" stage? I don't see it being used anywhere

2025-01-01 23:10 UTC, frol commented on Dockerfile
> +# 支持传递 GLIBC_VERSION 参数
Please, use English for all the comments

2025-01-01 23:11 UTC, race-of-sloths commented
@frol Thank you for calling!
    
@ChaimHong Thank you for the contribution! Join [Race of Sloths](https://race-of-sloths.com) by simply mentioning me in your comment/PRs description and start collecting Sloth Points through contributions to open source projects.

<details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/ChaimHong)

For maintainers:
- Score pull requests that participate in the Race of Sloths and receive a reward
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Invite contributor** `@race-of-sloths invite` to invite the contributor to participate in a race or include it, if it's already a runner.
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

2025-01-02 01:59 UTC, ChaimHong commented on Dockerfile
> +FROM alpine:3.20 AS remote-builder
just for builder. I want to use the logic of retaining remote builds. This is the advantage of Dockerfile. The usage like this 
`docker buildx build --platform linux/arm64,linux/amd64 --build-arg GLIBC_VERSION=2.39 --target remote-builder -t alpine-glibc:2.39 .`

2025-01-02 02:39 UTC, ChaimHong commented on Dockerfile
> +# 支持传递 GLIBC_VERSION 参数
done. @race-of-sloths

2025-01-02 02:53 UTC, ChaimHong commented on APKBUILD
> +  esac
yes, it works fine.  can try 
- amd64:`docker run -it --rm  --platform linux/amd64 chaimhong/alpine-glibc:2.39 /usr/glibc-compat/lib/libc.so.6`
- arm64: `docker run -it --rm  --platform linux/arm64 chaimhong/alpine-glibc:2.39 /usr/glibc-compat/lib/libc.so.6`

2025-01-06 06:02 UTC, ChaimHong reviewed
need u to review @frol

2025-03-29 16:43 UTC, frol approved these changes
@race-of-sloths score 13

2025-03-29 16:43 UTC, merged

2025-03-29 16:44 UTC, race-of-sloths commented
@frol Thank you for calling!
    
@ChaimHong Thank you for the contribution! Join [Race of Sloths](https://race-of-sloths.com) by simply mentioning me in your comment/PRs description and start collecting Sloth Points through contributions to open source projects.

<details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/ChaimHong)

For maintainers:
- Score pull requests that participate in the Race of Sloths and receive a reward
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Invite contributor** `@race-of-sloths invite` to invite the contributor to participate in a race or include it, if it's already a runner.
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

2025-04-09 02:19 UTC, race-of-sloths commented
### ⏰️ PR is already merged
It's too late to include us now. Include us before the merge next time!